version: "2.8"
services:
  db:
    container_name: dfe-complete-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file: .env.database
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql
volumes:
  sql-server-data:
