version: "3.8"
services:
  test:
    build:
      context: .
      target: test
      args:
        RAILS_ENV: "test"
      cache_from:
        - app_test:latest
    image: app_test
    command: bundle exec rake
    ports:
      - "3000:3000"
    depends_on:
      test-db:
        condition: service_started
      test-redis:
        condition: service_started
    env_file:
       - .env.test
    environment:
      DATABASE_URL: sqlserver://sa:strongPassword&@test-db:1433/sip_test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      SECRET_KEY_BASE: secret
      CI: "true"
      SENTRY_ENV: test
      REDIS_URL: redis://test-redis:6379
    networks:
      - test-ci

  test-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: strongPassword&
    networks:
      - test-ci

  test-redis:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - test-ci

networks:
  test-ci:
