version: "3.8"
services:
  test:
    build:
      context: .
      target: test
      args:
        RAILS_ENV: "test"
    command: bundle exec rake
    ports:
      - "3000:3000"
    depends_on:
      - test-db
      - test-redis
    env_file:
       - .env.test
    environment:
      DATABASE_URL: postgres://postgres:password@test-db:5432/dfe-academies-test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      AUTO_FIX_FORMATTING: "true"
      SENTRY_ENV: test
      REDIS_URL: redis://127.0.0.1:6379
    volumes:
      - .:/srv/app
    tty: true
    stdin_open: true
    networks:
      - test

  test-db:
    image: postgres
    volumes:
      - dfe-academies-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dfe-academies-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test

  test-redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - dfe-academies-redis-data:/data
    networks:
      - test

networks:
  test:
volumes:
  dfe-academies-db-data:
  dfe-academies-redis-data:
