#!/bin/sh

# Run the test suite for the application. Optionally pass in a path to an
# individual test file to run a single test.

set -e

# Enable the running of this script from any subdirectory without moving to root
cd "$(dirname "$0")/../.."

if [ -n "$DEBUG" ]; then
  set -x
fi

echo "==> Updating..."
script/no-docker/update

echo "==> Staring SQL Server container..."
script/no-docker/database

AUTOMATICALLY_FIX_LINTING=true script/all/test "$@"
