#!/bin/sh

# Update application to run for its current checkout.

set -e

echo "==> Bootstrapping..."
script/no-docker/bootstrap

# Only run database tasks if we are not in ONLY_LINTING mode
if [ -z "$ONLY_LINTING" ]; then
  echo "==> Starting SQL Server container..."
  script/no-docker/database

  echo "==> Running database migrations..."
  bundle exec rails db:migrate

  echo "==> Running test database migrations..."
  RAILS_ENV="test" bundle exec rails db:migrate
fi
