services:
  app:
    hostname: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    user: complete
    volumes:
      - ..:/workspace:cached
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
      - tmp:/workspace/tmp
    working_dir: /workspace
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      DATABASE_USER: sa
      DATABASE_PASSWORD: P@ssw0rd
      DATABASE_HOST: db
      ACCEPT_EULA: Y

  redis:
    container_name: dfe-complete-redis-backing-service
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  db:
    container_name: dfe-complete-sql-backing-service
    image: mcr.microsoft.com/azure-sql-edge:latest
    env_file: .env.database
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data:
  redis-data:
  bundle:
  node_modules:
  # Tempfile directory is IO-heavy and we don't need to have its contents replicated on host
  tmp: