#!/bin/sh

# script/lint_and_format:
#
# Runs all erb_lint, standardrb, prettier and eslint
#
# When AUTO_FIX is set, fixing will take place if available
#
set -e

echo "--> Linting and formatting"

if [ -n "$AUTO_FIX" ]; then
  echo "--> Auto fixing is enabled"

  echo "==> running Standardrb"
  bin/standardrb -f simple --fix
  echo "==> finished Standardrb"

  echo "==> running erb_lint"
  bin/erb_lint --lint-all --autocorrect
  echo "==> finished erb_lint"

  echo "==> running Prettier"
  yarn run lint:format:fix
  echo "==> finished Prettier"

  echo "==> running StandardJS"
  yarn run lint:js:fix
  echo "==> finished StandardJS"

else
  echo "--> Auto fixing is disabled"

  echo "==> running Standardrb"
  bin/standardrb -f simple
  echo "==> finished Standardrb"

  echo "==> running erb_lint"
  bin/erb_lint --lint-all
  echo "==> finished erb_lint"

  echo "==> running Prettier"
  yarn run lint:format
  echo "==> finished Prettier"

  echo "==> running StandardJS"
  yarn run lint:js
  echo "==> finished StandardJS"

fi

echo "--> Finshed linting and formatting"
