#!/bin/sh
# script/server:
#
# Make sure the backing services are running and starts the application

# make sure backing services are up
script/start_backing_services

# run the applcation
bin/rails server
