#!/bin/sh
# script/stop_backing_services:
#
# Make sure the backing services are running

echo "==> Checking backing services"
if docker compose ps | grep -q "dfe-complete-sql-backing-service\|Up"; then
  echo "--> Stoping backing services with docker-compose.yml"
  docker compose -f docker-compose.yml down
fi
