class Export::Conversions::AllDataCsvExportService < Export::CsvExportService
  COLUMN_HEADERS = %i[
    school_name
    school_urn
    project_type
    academy_name
    academy_urn
    academy_dfe_number
    incoming_trust_name
    local_authority_name
    region
    diocese_name
    provisional_conversion_date
    conversion_date
    academy_order_type
    two_requires_improvement
    advisory_board_date
    advisory_board_conditions
    risk_protection_arrangement
    risk_protection_arrangement_reason
    all_conditions_met
    completed_grant_payment_certificate_received
    school_type
    school_age_range
    school_phase
    reception_to_six_years
    seven_to_eleven_years
    twelve_or_above_years
    school_address_1
    school_address_2
    school_address_3
    school_address_town
    school_address_county
    school_address_postcode
    school_sharepoint_folder
    conversion_type
    incoming_trust_ukprn
    incoming_trust_identifier
    incoming_trust_companies_house_number
    incoming_trust_address_1
    incoming_trust_address_2
    incoming_trust_address_3
    incoming_trust_address_town
    incoming_trust_address_county
    incoming_trust_address_postcode
    incoming_trust_sharepoint_link
    project_created_by_name
    project_created_by_email
    assigned_to_name
    team_managing_the_project
    main_contact_name
    headteacher_contact_name
    headteacher_contact_role
    headteacher_contact_email
    local_authority_contact_name
    local_authority_contact_email
    incoming_trust_main_contact_name
    incoming_trust_main_contact_email
    outgoing_trust_main_contact_name
    outgoing_trust_main_contact_email
    incoming_trust_ceo_contact_name
    incoming_trust_ceo_contact_role
    incoming_trust_ceo_contact_email
    solicitor_contact_name
    solicitor_contact_email
    diocese_contact_name
    diocese_contact_email
    mp_name
    mp_constituency
    mp_email
    mp_address_1
    mp_address_2
    mp_address_3
    mp_address_postcode
    director_of_child_services_name
    director_of_child_services_email
    director_of_child_services_role
  ]

  def initialize(projects)
    @projects = projects
  end
end
