#!/bin/sh

# Run linting, formatting and schema tests.
#
# Do not set AUTO_FIX_FORMATTING if you want to disable linter fixing

set -e

echo "==> Running linting/formatting tests..."

if [ -n "$AUTO_FIX_FORMATTING" ]; then
  echo "==> Formatting files..."
  yarn run lint:format:fix
else
  echo "==> Checking formatting..."
  yarn run lint:format
fi

echo "==> Running ShellCheck..."
for file in $(git ls-files script/*)
do
  shellcheck -x "$file"
done

if [ -n "$AUTO_FIX_FORMATTING" ]; then
  echo "==> Linting ERB in autocorrect mode..."
  bundle exec erblint --lint-all --autocorrect
else
  echo "==> Linting ERB..."
  bundle exec erblint --lint-all
fi
if [ -n "$AUTO_FIX_FORMATTING" ]; then
  echo "==> Linting Ruby in fix mode..."
  bundle exec standardrb --fix
else
  echo "==> Linting Ruby..."
  bundle exec standardrb
fi

if [ -n "$AUTO_FIX_FORMATTING" ]; then
  echo "==> Linting JS in fix mode..."
  yarn run lint:js:fix
else
  echo "==> Linting JS..."
  yarn run lint:js
fi
