#!/bin/sh

# Run the test suite for the application. Optionally pass in a path to an
# individual test file to run a single test.
#
# Do not set AUTOMATICALLY_FIX_LINTING if you want to disable linter fixing

set -e

TEST_FILES=$1

if [ -n "$TEST_FILES" ]; then
  echo "==> Running the tests matching '$TEST_FILES'..."
  bundle exec rspec "$TEST_FILES"
else
  script/all/test-linting
  script/all/test-application
fi
