name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

jobs:
  build-image:
    name: Prepare Image
    uses: ./.github/workflows/1-build-image.yml
    with:
      version: development

  push-image:
    name: Push to Azure Container Registry
    uses: ./.github/workflows/2-push-image.yml
    with:
      environment: ${{ inputs.environment }}

  update-container:
    name: Restart Container
    uses: ./.github/workflows/3-update-container.yml
    with:
      environment: ${{ inputs.environment }}
