name: CI / Ruby / Accessibility

on:
  workflow_call:

env:
  DOCKER_IMAGE: complete-app

jobs:
  accessibility-checks:
    name: Accessibility checks
    runs-on: ubuntu-latest
    # Service containers to run
    services:
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      sql:
        image: mcr.microsoft.com/azure-sql-edge:latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: strongPassword&

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DOCKER_IMAGE }}-ci
          path: /tmp/${{ env.DOCKER_IMAGE }}-ci.tar

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.DOCKER_IMAGE }}-ci.tar

      - name: Run accessibility checks
        env:
          DATABASE_URL: "sqlserver://sa:strongPassword&@sql:1433/sip_test"
          DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
          SECRET_KEY_BASE: "secret"
          SENTRY_ENV: "test"
          REDIS_URL: "redis://redis:6379"
          NO_COVERAGE: "true"
          CI: "true"
        run: |
          echo "==> Running accessibility checks..."
          docker run --rm \
            -e DATABASE_URL \
            -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL \
            -e SECRET_KEY_BASE \
            -e SENTRY_ENV \
            -e REDIS_URL \
            -e CI \
            -e NO_COVERAGE \
            --env-file .env.test \
            --name app \
            ${{ env.DOCKER_IMAGE }}-ci \
            ./script/all/test
