name: Deploy to environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}-${{ github.run_number }}

env:
  IMAGE_NAME: complete-app

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-24.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      branch: ${{ steps.var.outputs.branch }}
      checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
      date: ${{ steps.var.outputs.date }}
      image-name: ${{ steps.var.outputs.image-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: var
        run: |
          GIT_REF=${{ github.ref_name }}
          GIT_BRANCH=${GIT_REF##*/}
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          TIME="$(date)"
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT
          echo "date=${TIME}" >> $GITHUB_OUTPUT
          echo "image-name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

  build-import:
    name: Build & Import
    runs-on: ubuntu-24.04
    needs: [ set-env ]
    environment: ${{ needs.set-env.outputs.environment }}
    permissions:
      attestations: write
      packages: write
      id-token: write

    steps:
      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/build@v5.2.1
        with:
          image-name: ${{ needs.set-env.outputs.image-name }}
          build-args: |
            RAILS_ENV=development
            CURRENT_GIT_SHA="${{ needs.set-env.outputs.checked-out-sha }}"
            TIME_OF_BUILD="${{ needs.set-env.outputs.date }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/import@v5.2.1
        with:
          image-name: ${{ needs.set-env.outputs.image-name }}
          azure-acr-name: ${{ secrets.ACR_NAME }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-acr-client-id: ${{ secrets.ACR_CLIENT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.ACR_CLIENT_ID || '' }}

  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: [ set-env, build-import ]
    environment: ${{ needs.set-env.outputs.environment }}
    permissions:
      id-token: write
    strategy:
      matrix:
        container_app: [
          "web",
          "worker"
        ]
        include:
          - container_app: "web"
            aca_name: "ACA_CONTAINERAPP_NAME"
            aca_client_id: "ACA_CLIENT_ID"
          - container_app: "worker"
            aca_name: "ACA_CONTAINERAPP_WORKER_NAME"
            aca_client_id: "ACA_WORKER_CLIENT_ID"
    steps:
      - id: annotate
        run: echo "ANNOTATE_RELEASE=${{ matrix.container_app == 'web' && 'yes' || 'no' }}" >> $GITHUB_ENV

      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/deploy@v5.2.1
        with:
          image-name: ${{ needs.set-env.outputs.image-name }}
          annotate-release: ${{ env.ANNOTATE_RELEASE }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-acr-name: ${{ secrets.ACR_NAME }}
          azure-aca-client-id: ${{ secrets[matrix.aca_client_id] }}
          azure-aca-name: ${{ secrets[matrix.aca_name] }}
          azure-aca-resource-group: ${{ secrets.ACA_RESOURCE_GROUP }}
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}
          AZURE_ACA_CLIENT_ID: ${{ secrets.ACA_CLIENT_ID || '' }}
