name: CI / Image / Push

on:
  workflow_run:
    workflows: [CI / Image / Build]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

env:
  DOCKER_IMAGE: complete-app

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-22.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      branch: ${{ steps.var.outputs.branch }}
      checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - id: var
        run: |
          GIT_REF=${{ github.ref }}
          GIT_BRANCH=${GIT_REF##*/}
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT

  push-image:
    name: Push to Azure Container Registry
    runs-on: ubuntu-22.04
    needs: [ set-env ]
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DOCKER_IMAGE }}-development
          path: /tmp/${{ env.DOCKER_IMAGE }}-development.tar

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.DOCKER_IMAGE }}-development.tar

      - name: Azure Container Registry login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AZURE_ACR_CLIENTID }}
          password: ${{ secrets.AZURE_ACR_SECRET }}
          registry: ${{ secrets.AZURE_ACR_URL }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          target: web
          build-args: |
            RAILS_ENV=development
          tags: |
            ${{ secrets.AZURE_ACR_URL }}/${{ env.DOCKER_IMAGE }}:${{ needs.set-env.outputs.branch }}
            ${{ secrets.AZURE_ACR_URL }}/${{ env.DOCKER_IMAGE }}:sha-${{ needs.set-env.outputs.checked-out-sha }}
            ${{ secrets.AZURE_ACR_URL }}/${{ env.DOCKER_IMAGE }}:latest
          push: true
