name: Update Container Apps
run-name: Deployment for '${{ inputs.environment }}' - `${{ inputs.branch }}`

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      image:
        required: true
        type: string

env:
  AZ_CLI_VER: 2.45.0

jobs:
  update-image:
    name: Update revision with new image
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
    - name: Azure login with ACA credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_ACA_CREDENTIALS }}

    - name: Update Azure Container Apps Revision
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name ${{ secrets.AZURE_ACA_NAME }} \
            --resource-group ${{ secrets.AZURE_ACA_RESOURCE_GROUP }} \
            --image ${{ inputs.image }} \
            --output none

    - name: Azure login with ACA Worker credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_ACA_WORKER_CREDENTIALS }}

    - name: Update Azure Container Apps Worker Revision
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ env.AZ_CLI_VER }}
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name ${{ secrets.AZURE_ACA_NAME }}-worker \
            --resource-group ${{ secrets.AZURE_ACA_RESOURCE_GROUP }} \
            --image ${{ inputs.image }} \
            --output none
