name: Zap

on:
  pull_request:

jobs:
  specs:
    name: Zap
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and cache
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.checks
          build-args: |
            RAILS_ENV=test
          push: false
          load: true
          tags: complete-app:latest
          cache-from: type=gha
      -
        name: Run Zap
        run: |
          docker compose -p complete-app -f docker-compose.zap.yml \
          run --rm zap zap-full-scan.py -t http://application
